[package]
name = "sachbearbeiter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jq_lang = "0.1.0"
clap = "3.0.0-beta.4"
color-eyre = "0.5.11"
serde = "1.0.130"
serde_json = "1.0.67"